import random
import json
from locust import HttpUser, FastHttpUser, task, between

PRODUCT_IDS = list(range(1, 11)) 

def make_update_body(pid: int):
    return {
        "id": pid,
        "name": f"LoadTestProduct{pid}",
        "price": round(random.uniform(5, 50), 2),
        "description": "Generated by Locust test"
    }

# ---- Scenario 1: HttpUser ----
class ApiHttpUser(HttpUser):
    wait_time = between(0.5, 2)

    @task(9) 
    def get_product(self):
        pid = random.choice(PRODUCT_IDS)
        self.client.get(f"/v1/products/{pid}", name="/products/{id}")

    @task(1)  
    def update_product(self):
        pid = random.choice(PRODUCT_IDS)
        self.client.post(
            f"/v1/products/{pid}/details",
            headers={"Content-Type": "application/json"},
            data=json.dumps(make_update_body(pid)),
            name="/v1/products/{id}/details"
        )

# ---- Scenario 2: FastHttpUser ----
class ApiFastHttpUser(FastHttpUser):
    wait_time = between(0.5, 2)

    @task(9)
    def get_product(self):
        pid = random.choice(PRODUCT_IDS)
        self.client.get(f"/v1/products/{pid}", name="/products/{id}")

    @task(1)
    def update_product(self):
        pid = random.choice(PRODUCT_IDS)
        self.client.post(
            f"/v1/products/{pid}/details",
            headers={"Content-Type": "application/json"},
            data=json.dumps(make_update_body(pid)),
            name="/v1/products/{id}/details"
        )
